### ISSUE TITLE
別表の扱いについて

### ISSUE THREAD

**Issue by Heat-Exchange** [law-of-japan/repository-management-guideline#1]
法文内に別表が提示されている場合はどのファイルに表を作成すればよいでしょうか

**Comment by pinfort** [comment]
別表については、附則のように、別ファイルを用意することとします。
ファイル名をどうするか考えますね

**Comment by pinfort** [comment]
案があれば言ってください。

**Comment by Heat-Exchange** [comment]
~~それはもちろんbeppyo.mdに決まってるじゃないですか~~

annexed_table.mdとかいかがでしょう

**Comment by pinfort** [comment]
~~beppyo.md、実に日本的で素晴らしいですね~~

annexed_tableがわかりやすくて良さそうですね。

**Comment by pinfort** [comment]
annexed_table.mdとすることにします。
