### ISSUE TITLE
編、章、節、款、目が別れている場合のヘッダーについて

### ISSUE THREAD

**Issue by Heat-Exchange** [law-of-japan/repository-management-guideline#2]
exampleでは、章と条文からなる場合、ヘッダーは次のように記載されています。

- chapter1.md
```Markdown
# 第一章　総則
## 第一条　〇〇

~~~~

```
- chapter2.md 
```Markdown
# 第二章　
## 第○条　〇〇

~~~~

```

章の下に節が置かれている場合、あるいは編、章、節、款、目が別れている場合はディレクトリを分けて階層構造を作ることになっています。例えば、

- chapter1
  - section1.md
  - section2.md

という階層構造があったとします。このとき、上位の層の表題はsection1のみに記載するべきでしょうか。それとも、下層のすべてのファイルに記載するべきでしょうか。
具体的には、

- chapter1/section1.md
```Markdown
# 第一章
## 第一節
### 第一条

~~~

```

- chapter1/section2.md
```Markdown
## 第二節
### 第○条
~~~

```
のように、上層の表題は最下層の一番最初のファイルにのみ記載するべきでしょうか。
それとも、

- chapter1/section1.md
```Markdown
# 第一章
## 第一節
### 第一条

~~~

```

- chapter1/section2.md
```Markdown
# 第一章
## 第二節
### 第○条

~~~

```
といったように、上層の表題は最下層のすべてのファイルに表題を記載するべきでしょうか

**Comment by pinfort** [comment]
ここにissueを上げてくれていたんですね。
基本的に、全ファイルに表題を記載して欲しいです。

**Comment by Heat-Exchange** [comment]
承知しました。
ありがとうございます。

**Comment by pinfort** [comment]
現時点では上の通りですが、 #3 の結論によっては変更が生じる可能性があるのでそれだけ...
