### ISSUE TITLE
法令中での他法令へのリンク

### ISSUE THREAD

**Issue by pinfort** [law-of-japan/repository-management-guideline#5]
ある条文が、他法令や同法令の他条文を参照している場合、リンクをつけると親切かと思いますが、つけるべきでしょうか。これには、利用者の利便に資するものの、後からリンク追加を行わないといけなくなるというデメリットがあります。

例）労働基準法第百二十四条

[鉱業法]の一部を次のように改正する。

例2）労働基準法第百二十七条

[第十八条]第二項、[第四十九条]、[第五十七条]、[第六十条]乃至[第六十三条]、[第八十九条]、[第九十五条]及び[第百六条]乃至[第百八条]の規定は、この法律施行の日から六箇月間は、これを適用しない。

以上の例の[]の部分にリンクをつけるか、という問題です。

**Comment by pinfort** [comment]
@peijun  これどうする？あった方がいいと思うんだけど、やるなら労働基準法からでもやりたい

**Comment by peijun** [comment]
あったほうがいいと思う
莫大な編集量にはなるけど

**Comment by pinfort** [comment]
やります
